# File generated by CompCert 3.16
# Command line: -o foo.s -S compiler_test/foo.b
	.section	"license","a",%progbits
	.balign 1
	.globl	___license
___license:
	.byte	71
	.byte	80
	.byte	76
	.byte	0
	.type	___license, @object
	.size	___license, . - ___license
	.data
	.balign 8
	.globl	__stringlit_1
__stringlit_1:
	.ascii	"Hello\000"
	.type	__stringlit_1, @object
	.size	__stringlit_1, . - __stringlit_1
	.section	"xdp","ax",%progbits
	.balign 2
	.globl xdp_packet_count
xdp_packet_count:
	.cfi_startproc
	r1 = "__stringlit_1" + 0 ll
	w2 = 6
	call 6
	w0 = 2
	exit
	.cfi_endproc
	.type	xdp_packet_count, @function
	.size	xdp_packet_count, . - xdp_packet_count
