# File generated by CompCert 3.15
# Command line: -D __bpf_helper_as_extern__ -S -o ebpf/test/hash_map_example2/hash_map_example2.s ebpf/test/hash_map_example2/hash_map_example2.c
	.comm	counter_table, 16, 8
	.comm	uid, 8, 4
	.section	.rodata
	.balign 1
____fmt:
	.byte	72
	.byte	101
	.byte	108
	.byte	108
	.byte	111
	.byte	32
	.byte	97
	.byte	102
	.byte	116
	.byte	101
	.byte	114
	.byte	32
	.byte	98
	.byte	112
	.byte	102
	.byte	32
	.byte	99
	.byte	97
	.byte	108
	.byte	108
	.byte	32
	.byte	116
	.byte	111
	.byte	32
	.byte	103
	.byte	101
	.byte	116
	.byte	32
	.byte	117
	.byte	105
	.byte	100
	.byte	32
	.byte	97
	.byte	110
	.byte	100
	.byte	32
	.byte	103
	.byte	105
	.byte	100
	.byte	0
	.type	____fmt, @object
	.size	____fmt, . - ____fmt
	.text
	.balign 2
	.globl hello
hello:
	.cfi_startproc
	r0 = r10
	r10 -= 32
	*(u64 *)(r10 + 0) = r0
	*(u64 *)(r10 + 8) = r6
	r0 = 0
	*(u64 *)(r10 + 16) = r0
	r6 = 4294967295
	call bpf_get_current_uid_gid
	r2 = "uid" + 0 ll
	r0 &= r6
	*(u64 *)(r2 + 0) = r0
	r1 = "____fmt" + 0 ll
	w2 = 40
	call bpf_trace_printk
	r1 = "counter_table" + 0 ll
	r2 = "uid" + 0 ll
	call bpf_map_lookup_elem
	if r0 == 0 goto .L100
	r0 = *(u64 *)(r0 + 0)
	*(u64 *)(r10 + 16) = r0
.L100:
	r0 = *(u64 *)(r10 + 16)
	r0 += 1
	*(u64 *)(r10 + 16) = r0
	r1 = "counter_table" + 0 ll
	r2 = "uid" + 0 ll
	r3 = r10
	r3 += 16
	r4 = 0
	call bpf_map_update_elem
	w0 = 0
	r6 = *(u64 *)(r10 + 8)
	r10 += 32
	exit
	.cfi_endproc
	.type	hello, @function
	.size	hello, . - hello
	.text
	.balign 2
	.globl main
main:
	.cfi_startproc
	r0 = r10
	r10 -= 16
	*(u64 *)(r10 + 0) = r0
	r1 = 0
	call hello
	w0 = 0
	r10 += 16
	exit
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
