# File generated by CompCert 3.16
# Command line: -D__bpf_helper_as_extern__ -fpacked-structs -I/. -o xdp1.s -S compiler_test/ebpf_test/xdp1.c
	.data
	.balign 4
	.globl	counter
counter:
	.long	0
	.type	counter, @object
	.size	counter, . - counter
	.section	.rodata
	.balign 1
____fmt:
	.byte	37
	.byte	100
	.byte	0
	.type	____fmt, @object
	.size	____fmt, . - ____fmt
	.section	"xdp","ax",%progbits
	.balign 2
	.globl packet_count
packet_count:
	.cfi_startproc
	r1 = "____fmt" + 0 ll
	w2 = 3
	r3 = "counter" + 0 ll
	w3 = *(u32 *)(r3 + 0)
	call 6
	r1 = "counter" + 0 ll
	w0 = *(u32 *)(r1 + 0)
	w0 += 1
	*(u32 *)(r1 + 0) = w0
	w0 = 2
	exit
	.cfi_endproc
	.type	packet_count, @function
	.size	packet_count, . - packet_count
	.section	"license","aw",%progbits
	.balign 1
	.globl	LICENSE
LICENSE:
	.byte	68
	.byte	117
	.byte	97
	.byte	108
	.byte	32
	.byte	66
	.byte	83
	.byte	68
	.byte	47
	.byte	71
	.byte	80
	.byte	76
	.byte	0
	.type	LICENSE, @object
	.size	LICENSE, . - LICENSE
