; File generated by CompCert 3.15
; Command line: -S compiler_test/cond1.c -o compiler_test/cond1.s
	.text
	.balign 4
	.globl _main
_main:
	.cfi_startproc
	mov	x15, sp
	sub	sp, sp, #16
	.cfi_adjust_cfa_offset	16
	str	x15, [sp, #0]
	str	x30, [sp, #8]
	.cfi_rel_offset	x30, 8
	orr	w0, wzr, #3
	ldr	x30, [sp, #8]
	add	sp, sp, #16
	ret	x30
	.cfi_endproc
