; File generated by CompCert 3.15
; Command line: -S compiler_test/div1.c -o compiler_test/div1.s
	.cstring
	.balign 1
___stringlit_1:
	.ascii	"%d\000"
	.text
	.balign 4
	.globl _div
_div:
	.cfi_startproc
	mov	x15, sp
	sub	sp, sp, #16
	.cfi_adjust_cfa_offset	16
	str	x15, [sp, #0]
	str	x30, [sp, #8]
	.cfi_rel_offset	x30, 8
	sdiv	w0, w0, w1
	sbfiz	w0, w0, 0, 16
	ldr	x30, [sp, #8]
	add	sp, sp, #16
	ret	x30
	.cfi_endproc
	.text
	.balign 4
	.globl _main
_main:
	.cfi_startproc
	mov	x15, sp
	sub	sp, sp, #32
	.cfi_adjust_cfa_offset	32
	str	x15, [sp, #8]
	str	x30, [sp, #16]
	.cfi_rel_offset	x30, 16
	orr	w0, wzr, #8
	orr	w1, wzr, #2
	bl	_div
	sbfiz	w2, w0, 0, 16
	adrp	x0, ___stringlit_1@PAGE
	add	x0, x0, ___stringlit_1@PAGEOFF
	str	x2, [sp, #0]
	bl	_printf
	movz	w0, #0, lsl #0
	ldr	x30, [sp, #16]
	add	sp, sp, #32
	ret	x30
	.cfi_endproc
