# File generated by CompCert 3.15
# Command line: -D __bpf_helper_as_extern__ -S -o ebpf/test/simple/simple.s ebpf/test/simple/simple.c
	.text
	.balign 2
	.globl simple
simple:
	.cfi_startproc
	r0 = r10
	r10 -= 16
	*(u64 *)(r10 + 0) = r0
	w0 = 0
	r10 += 16
	exit
	.cfi_endproc
	.type	simple, @function
	.size	simple, . - simple
