# File generated by CompCert 3.15
# Command line: -D __bpf_helper_as_extern__ -S -o ebpf/test/hash_map_example1/hash_map_example1.s ebpf/test/hash_map_example1/hash_map_example1.c
	.comm	counter_table, 16, 8
	.text
	.balign 2
	.globl hello
hello:
	.cfi_startproc
	r0 = r10
	r10 -= 40
	*(u64 *)(r10 + 0) = r0
	*(u64 *)(r10 + 8) = r6
	r0 = 0
	*(u64 *)(r10 + 24) = r0
	r6 = 4294967295
	call bpf_get_current_uid_gid
	r0 &= r6
	*(u64 *)(r10 + 16) = r0
	r1 = "counter_table" + 0 ll
	r2 = r10
	r2 += 16
	call bpf_map_lookup_elem
	if r0 == 0 goto .L100
	r0 = *(u64 *)(r0 + 0)
	*(u64 *)(r10 + 24) = r0
.L100:
	r0 = *(u64 *)(r10 + 24)
	r0 += 1
	*(u64 *)(r10 + 24) = r0
	r1 = "counter_table" + 0 ll
	r2 = r10
	r2 += 16
	r3 = r10
	r3 += 24
	r4 = 0
	call bpf_map_update_elem
	w0 = 0
	r6 = *(u64 *)(r10 + 8)
	r10 += 40
	exit
	.cfi_endproc
	.type	hello, @function
	.size	hello, . - hello
