# File generated by CompCert 3.15
# Command line: -D __bpf_helper_as_extern__ -S -o ebpf/test/termination_check/termination_check.s ebpf/test/termination_check/termination_check.c
	.text
	.balign 2
	.globl main
main:
	.cfi_startproc
	r0 = r10
	r10 -= 40
	*(u64 *)(r10 + 0) = r0
.L100:
	w0 = 116
	*(u8 *)(r10 + 8) = w0
	w0 = 101
	*(u8 *)(r10 + 9) = w0
	w0 = 109
	*(u8 *)(r10 + 10) = w0
	w0 = 105
	*(u8 *)(r10 + 11) = w0
	w0 = 110
	*(u8 *)(r10 + 12) = w0
	w0 = 97
	*(u8 *)(r10 + 13) = w0
	w0 = 116
	*(u8 *)(r10 + 14) = w0
	w0 = 105
	*(u8 *)(r10 + 15) = w0
	w0 = 111
	*(u8 *)(r10 + 16) = w0
	w0 = 110
	*(u8 *)(r10 + 17) = w0
	w0 = 95
	*(u8 *)(r10 + 18) = w0
	w0 = 99
	*(u8 *)(r10 + 19) = w0
	w0 = 104
	*(u8 *)(r10 + 20) = w0
	w0 = 101
	*(u8 *)(r10 + 21) = w0
	w0 = 99
	*(u8 *)(r10 + 22) = w0
	w0 = 107
	*(u8 *)(r10 + 23) = w0
	w0 = 0
	*(u8 *)(r10 + 24) = w0
	r1 = r10
	r1 += 8
	w2 = 17
	call bpf_trace_printk
	goto .L100
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
