# File generated by CompCert 3.16
# Command line: -o foo.s -S compiler_test/foo.b
	.section	"xdp","ax",%progbits
	.balign 2
	.globl xdp_packet_count
xdp_packet_count:
	.cfi_startproc
	w0 = 2
	exit
	.cfi_endproc
	.type	xdp_packet_count, @function
	.size	xdp_packet_count, . - xdp_packet_count
