# File generated by CompCert 3.15
# Command line: -D __bpf_helper_as_extern__ -S -o ebpf/test/packet_count/packet_count.s ebpf/test/packet_count/packet_count.c
	.data
	.balign 4
	.globl	counter
counter:
	.long	0
	.type	counter, @object
	.size	counter, . - counter
	.text
	.balign 2
	.globl packet_count
packet_count:
	.cfi_startproc
	r0 = r10					// Moves the value of FP/SP to r0
	r10 -= 24                   // Makes space of 24 bytes in the stack 
	*(u64 *)(r10 + 0) = r0      // Stores the value of initial FP in r10 
	w0 = 37                     // Question??
	*(u8 *)(r10 + 8) = w0       // Stores w0 in one cell of the stack using 8 bytes 
	w0 = 100                    // Question??
	*(u8 *)(r10 + 9) = w0       // Stores w0 in r10+9
	w0 = 0                      // Reser w0 to 0
	*(u8 *)(r10 + 10) = w0      // Stores w0 to r10+10
	r1 = r10                    // Move FP to r1?? r1 should be argument which is xdp context here 
	r1 += 8                      
	w2 = 3                      
	r3 = "counter" + 0 ll
	w3 = *(u32 *)(r3 + 0)
	call bpf_trace_printk       
	r1 = "counter" + 0 ll
	w0 = *(u32 *)(r1 + 0)
	w0 += 1
	*(u32 *)(r1 + 0) = w0
	w0 = 2                      // Return value should be stored in r0
	r10 += 24                   // FP is only allowed to read in ebpf... FP is reset 
	exit
	.cfi_endproc
	.type	packet_count, @function
	.size	packet_count, . - packet_count
	.data
	.balign 1
	.globl	LICENSE
LICENSE:
	.byte	68
	.byte	117
	.byte	97
	.byte	108
	.byte	32
	.byte	66
	.byte	83
	.byte	68
	.byte	47
	.byte	71
	.byte	80
	.byte	76
	.byte	0
	.type	LICENSE, @object
	.size	LICENSE, . - LICENSE
