# File generated by CompCert 3.15
# Command line: -D __bpf_helper_as_extern__ -S -o ebpf/test/minimal/minimal.s ebpf/test/minimal/minimal.c
	.data
	.balign 1
	.globl	LICENSE
LICENSE:
	.byte	68
	.byte	117
	.byte	97
	.byte	108
	.byte	32
	.byte	66
	.byte	83
	.byte	68
	.byte	47
	.byte	71
	.byte	80
	.byte	76
	.byte	0
	.type	LICENSE, @object
	.size	LICENSE, . - LICENSE
	.data
	.balign 4
	.globl	my_pid
my_pid:
	.long	0x0, 0x0
	.type	my_pid, @object
	.size	my_pid, . - my_pid
	.section	.rodata
	.balign 1
____fmt:
	.byte	72
	.byte	101
	.byte	108
	.byte	108
	.byte	111
	.byte	32
	.byte	102
	.byte	114
	.byte	111
	.byte	109
	.byte	32
	.byte	109
	.byte	105
	.byte	110
	.byte	105
	.byte	109
	.byte	97
	.byte	108
	.byte	33
	.byte	0
	.type	____fmt, @object
	.size	____fmt, . - ____fmt
	.section	.rodata
	.balign 1
____fmt__1:
	.byte	66
	.byte	80
	.byte	70
	.byte	32
	.byte	116
	.byte	114
	.byte	105
	.byte	103
	.byte	103
	.byte	101
	.byte	114
	.byte	101
	.byte	100
	.byte	32
	.byte	102
	.byte	114
	.byte	111
	.byte	109
	.byte	32
	.byte	80
	.byte	73
	.byte	68
	.byte	32
	.byte	37
	.byte	100
	.byte	46
	.byte	10
	.byte	0
	.type	____fmt__1, @object
	.size	____fmt__1, . - ____fmt__1
	.text
	.balign 2
	.globl handle_tp
handle_tp:
	.cfi_startproc
	r0 = r10
	r10 -= 16
	*(u64 *)(r10 + 0) = r0
	r1 = "____fmt" + 0 ll
	w2 = 20
	call bpf_trace_printk
	call bpf_get_current_pid_tgid
	r3 = r0
	r3 s>>= 32
	r4 = "my_pid" + 0 ll
	r1 = *(u64 *)(r4 + 0)
	if r3 == r1 goto .L100
	w0 = 0
	goto .L101
.L100:
	r1 = "____fmt__1" + 0 ll
	w2 = 28
	call bpf_trace_printk
	w0 = 0
.L101:
	r10 += 16
	exit
	.cfi_endproc
	.type	handle_tp, @function
	.size	handle_tp, . - handle_tp
	.text
	.balign 2
	.globl main
main:
	.cfi_startproc
	r0 = r10
	r10 -= 16
	*(u64 *)(r10 + 0) = r0
	r1 = 0
	call handle_tp
	w0 = 0
	r10 += 16
	exit
	.cfi_endproc
	.type	main, @function
	.size	main, . - main
