# File generated by CompCert 3.15
# Command line: -D __bpf_helper_as_extern__ -S -o ebpf/test/minimal/minimal.s ebpf/test/minimal/minimal.c
	.data
	.balign 1
	.globl	LICENSE
LICENSE:
	.byte	68
	.byte	117
	.byte	97
	.byte	108
	.byte	32
	.byte	66
	.byte	83
	.byte	68
	.byte	47
	.byte	71
	.byte	80
	.byte	76
	.byte	0
	.type	LICENSE, @object
	.size	LICENSE, . - LICENSE
	.data
	.balign 4
	.globl	my_pid
my_pid:
	.long	0
	.type	my_pid, @object
	.size	my_pid, . - my_pid
	.text
	.balign 2
	.globl handle_tp
handle_tp:
	.cfi_startproc
	r0 = r10
	r10 -= 48
	*(u64 *)(r10 + 0) = r0
	call bpf_get_current_pid_tgid
	r3 = r0
	r3 >>= 32
	r3 &= -1
	r5 = "my_pid" + 0 ll
	w5 = *(u32 *)(r5 + 0)
	if w3 == w5 goto .L100
	w0 = 0
	goto .L101
.L100:
	w2 = 66
	*(u8 *)(r10 + 8) = w2
	w4 = 80
	*(u8 *)(r10 + 9) = w4
	w1 = 70
	*(u8 *)(r10 + 10) = w1
	w1 = 32
	*(u8 *)(r10 + 11) = w1
	w4 = 116
	*(u8 *)(r10 + 12) = w4
	w2 = 114
	*(u8 *)(r10 + 13) = w2
	w5 = 105
	*(u8 *)(r10 + 14) = w5
	w2 = 103
	*(u8 *)(r10 + 15) = w2
	w2 = 103
	*(u8 *)(r10 + 16) = w2
	w5 = 101
	*(u8 *)(r10 + 17) = w5
	w4 = 114
	*(u8 *)(r10 + 18) = w4
	w1 = 101
	*(u8 *)(r10 + 19) = w1
	w0 = 100
	*(u8 *)(r10 + 20) = w0
	w4 = 32
	*(u8 *)(r10 + 21) = w4
	w0 = 102
	*(u8 *)(r10 + 22) = w0
	w4 = 114
	*(u8 *)(r10 + 23) = w4
	w2 = 111
	*(u8 *)(r10 + 24) = w2
	w1 = 109
	*(u8 *)(r10 + 25) = w1
	w5 = 32
	*(u8 *)(r10 + 26) = w5
	w4 = 80
	*(u8 *)(r10 + 27) = w4
	w4 = 73
	*(u8 *)(r10 + 28) = w4
	w4 = 68
	*(u8 *)(r10 + 29) = w4
	w0 = 32
	*(u8 *)(r10 + 30) = w0
	w4 = 37
	*(u8 *)(r10 + 31) = w4
	w0 = 100
	*(u8 *)(r10 + 32) = w0
	w0 = 46
	*(u8 *)(r10 + 33) = w0
	w0 = 10
	*(u8 *)(r10 + 34) = w0
	w1 = 0
	*(u8 *)(r10 + 35) = w1
	r1 = r10
	r1 += 8
	w2 = 28
	call bpf_trace_printk
	w0 = 0
.L101:
	r10 += 48
	exit
	.cfi_endproc
	.type	handle_tp, @function
	.size	handle_tp, . - handle_tp
